/*
 * JZebraApplet.java
 *
 * Created on July 28, 2008, 11:15 AM
 */

package jzebra;

import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author  tfino
 */
public class JZebraApplet extends javax.swing.JApplet {

    /** Initializes the applet JZebraApplet */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    setLookAndFeel();
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    @Override
    public void destroy() {
        this.stop();
        super.destroy();
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(jzebra.JZebraApp.class).getContext().getActionMap(JZebraApplet.class, this);
        printButton.setAction(actionMap.get("printCard")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jzebra.JZebraApp.class).getContext().getResourceMap(JZebraApplet.class);
        printButton.setText(resourceMap.getString("printButton.text")); // NOI18N
        printButton.setName("printButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printButton)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printButton)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public Task printCard() {
        printButton.setEnabled(false);
        PrintCardTask task = null;
        try {
             task = new PrintCardTask(org.jdesktop.application.Application.getInstance(jzebra.JZebraApp.class));
        }
        catch (Exception e) {
            JZebra.showError("A thread exception has been thrown trying to print your card:  " + 
                        e.getMessage() + ".   More details can be found in the Java Console.  " +
                        "If problem persists, close and reopen web browser.");
        }
        printButton.setEnabled(true);
        return task;
    }

    /**
     * 
     */
    private class PrintCardTask extends org.jdesktop.application.Task<Object, Void> {
        boolean error = false;
        PrintCardTask(org.jdesktop.application.Application app) {
            super(app);
        }
        @Override protected Object doInBackground() {
            JZebra.setCommands(JZebra.readFile("/jzebra/resources/eltron_p310.cfg"));
            JZebra.processArgs(JZebraApplet.this.buildArgs());
            error = !JZebra.print();
            return null;  // return your result
        }
        @Override protected void succeeded(Object result) {
            if (error) {
                System.out.println("Critical error printing your card");
                JZebra.showError("Critical error printing your card.  " + 
                        " Check to ensure your printer is configured properly.");
            }
            else {
                JZebra.showSuccess("Successfully sent card information to printer.");
            }
            printButton.setEnabled(true);
        }
    }

    /**
     * 
     */
    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (UnsupportedLookAndFeelException e) {}
        catch (ClassNotFoundException e) {}
        catch (InstantiationException e) {}
        catch (IllegalAccessException e) {}
    }
    
    private String[] buildArgs() {
        String args = "";
        
        ArrayList<String> params = new ArrayList<String>();
        params.add(this.getParameter("param1"));
        params.add(this.getParameter("param2"));
        params.add(this.getParameter("param3"));
        params.add(this.getParameter("param4"));
        params.add(this.getParameter("param5"));
        params.add(this.getParameter("param6"));
        params.add(this.getParameter("param7"));
        params.add(this.getParameter("param8"));
        params.add(this.getParameter("param9"));
        params.add(this.getParameter("param10"));
        params.add(this.getParameter("param11"));
        params.add(this.getParameter("param12"));
        params.add(this.getParameter("param13"));
        
        
        for (String s : params) {
            if (s != null && !s.equals("")) {
                args = args + "\n" + s;
            }
        }
        
        return args.split("\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables

}
