/*
 * JZebraView.java
 * Date: 2008-07-25
 * Author: A. Tres Finocchiaro
 * Liscense: GPL 3.0+
 */

package jzebra;

import java.awt.Color;
import java.awt.Image;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.standard.PrinterName;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class JZebraView extends FrameView {
    
    Image logo;
    boolean printLogo = true;
    
    /**
     * 
     * @param app
     */
    public JZebraView(SingleFrameApplication app) {
        super(app);
        initComponents();
        initCustomComponents();
    }
    
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = JZebraApp.getApplication().getMainFrame();
            aboutBox = new JZebraAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        JZebraApp.getApplication().show(aboutBox);
    }
    
    /**
     * 
     */
    private void initCustomComponents() {
        //JZebra.setLogo(loadLogo("/jzebra/resources/logo.bmp"));

        for (PrintService p : PrintServiceLookup.lookupPrintServices(null, null))
            printerComboBox.addItem(((PrinterName)p.getAttribute(PrinterName.class)).getValue());
        
        if (JZebra.getCommands() != null && !JZebra.getCommands().trim().equals(""))
            printCommandsArea.setText(JZebra.getCommands());
        

        if (JZebra.getPrintService() != null) {
            PrinterName pn = (PrinterName)JZebra.getPrintService().getAttribute(PrinterName.class);
            printerComboBox.setSelectedItem(pn.getValue());
        }
        printCommandsArea.setCaretPosition(0);
        getRootPane().setDefaultButton(printButton);
        getFrame().setIconImage(JZebra.loadImage("/jzebra/resources/creditcards.png"));
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        printCommandsPane = new javax.swing.JScrollPane();
        printCommandsArea = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        printerComboBox = new javax.swing.JComboBox();
        helpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        mainPanel.setName("mainPanel"); // NOI18N

        printCommandsPane.setName("printCommandsPane"); // NOI18N

        printCommandsArea.setColumns(20);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jzebra.JZebraApp.class).getContext().getResourceMap(JZebraView.class);
        printCommandsArea.setFont(resourceMap.getFont("printCommandsArea.font")); // NOI18N
        printCommandsArea.setRows(5);
        printCommandsArea.setText(resourceMap.getString("printCommandsArea.text")); // NOI18N
        printCommandsArea.setName("printCommandsArea"); // NOI18N
        printCommandsPane.setViewportView(printCommandsArea);

        printButton.setIcon(resourceMap.getIcon("printButton.icon")); // NOI18N
        printButton.setMnemonic('p');
        printButton.setText(resourceMap.getString("printButton.text")); // NOI18N
        printButton.setToolTipText(resourceMap.getString("printButton.toolTipText")); // NOI18N
        printButton.setName("printButton"); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        printerComboBox.setToolTipText(resourceMap.getString("printerComboBox.toolTipText")); // NOI18N
        printerComboBox.setName("printerComboBox"); // NOI18N
        printerComboBox.setRenderer(new PrinterListCellRenderer());

        helpButton.setIcon(resourceMap.getIcon("helpButton.icon")); // NOI18N
        helpButton.setText(resourceMap.getString("helpButton.text")); // NOI18N
        helpButton.setToolTipText(resourceMap.getString("helpButton.toolTipText")); // NOI18N
        helpButton.setName("helpButton"); // NOI18N
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                helpButtonMouseReleased(evt);
            }
        });
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printCommandsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerComboBox, 0, 177, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printCommandsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printButton)
                        .addComponent(jLabel1)
                        .addComponent(printerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

/**
 * 
 * @param evt
 */
private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
    try {
        if (JZebra.getPrintService() == null) {
            JZebra.setPrintService(JZebra.getBestPrinter(printerComboBox.getSelectedItem()));
        }
        JZebra.print(JZebra.getPrintService(), printCommandsArea.getText());
    }
    catch (PrintException p) {
        JZebra.showError(p);
    }
}//GEN-LAST:event_printButtonActionPerformed

private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
    printCommandsArea.setText(JZebra.readFile("/jzebra/resources/eltron_p310.cfg"));
    printCommandsArea.setCaretPosition(0);
}//GEN-LAST:event_helpButtonActionPerformed

private void helpButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMousePressed
    printCommandsArea.setName("" + printCommandsArea.getForeground().getRGB());
    printCommandsArea.setForeground(Color.RED);
    
}//GEN-LAST:event_helpButtonMousePressed

private void helpButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseReleased
    printCommandsArea.setForeground(Color.getColor(printCommandsArea.getName()));
}//GEN-LAST:event_helpButtonMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton printButton;
    private javax.swing.JTextArea printCommandsArea;
    private javax.swing.JScrollPane printCommandsPane;
    private javax.swing.JComboBox printerComboBox;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
}
